'''
Created on 30/07/2014

@author: s4361277
'''
myHydrophobics = "FLIMVPAWG"
mySequence = "MCGTEGPNFYVPFSNKTGVVRSPFEAPQYYLAEPWQFSMLAAYMFLLIMLGFPIN"\
    + "FLTLYVTVQHKKLRTPLNYILLNLAVADLFMVFGGFTTTLYTSLHGYFVFGPTGCNLEGFFA"\
    + "TLGGEIALWSLVVLAIERYVVVCKPMSNFRFGENHAIMGVAFTWVMALACAAPPLVGWSRYI"\
    + "PEGMQCSCGIDYYTPHEETNNESFVIYMFVVHFIIPLIVIFFCYGQLVFTVKEAAAQQQESA"\
    + "TTQKAEKEVTRMVIIMVIAFLICWLPYAGVAFYIFTHQGSCFGPIFMTIPAFFAKTSAVYNP"\
    + "VIYIMMNKQFRNCMVTTLCCGKNPLGDDEASTTVSKTETSQVAPA"
mySequenceHydro = ""
for myaa in mySequence:
    #print "The amino acids is", myaa
    if myaa in myHydrophobics:
        mySequenceHydro += "*"
    else:
        mySequenceHydro += " "
print mySequence
print mySequenceHydro
